### PR TITLE
Personnel related table generation

### PR DESCRIPTION
**Pull request by brewgator**

### CODE REVIEW

**Review by davidallen1 — APPROVED** [review]
Everything looks good

**Review by pt-repos — COMMENTED** [review]
Do we need separated tables for Actors and Directors as they are simply mapping (A/D)ID to PersonID?
What if we directly use PersonID in acted_in and directed tables?

**Review by pt-repos — CHANGES_REQUESTED** [review]
directed.sql contains create command for acted_in table

**Comment by brewgator** [comment]
> Do we need separated tables for Actors and Directors as they are simply mapping (A/D)ID to PersonID?
> What if we directly use PersonID in acted_in and directed tables?

I was actually thinking about this this morning.  I think it would be ok to completely remove ActorID and DirectorID and instead just use PersonID.  There does need to be separate tables for each since you can technically be a director of a movie you are also staring in.

**Comment by brewgator** [comment]
I fixed the error in the directed table as well as updated Actor/Director IDs to link to PersonID directly instead of just creating a new id

**Comment by pt-repos** [comment]
> There does need to be separate tables for each since you can technically be a director of a movie you are also staring in.

This will be handled by the acted_in and directed tables. So the person can have an entry against the same movie_id in both the tables if they acted in and directed a movie.

**Comment by brewgator** [comment]
> > There does need to be separate tables for each since you can technically be a director of a movie you are also staring in.
> 
> This will be handled by the acted_in and directed tables. So the person can have an entry against the same movie_id in both the tables if they acted in and directed a movie.

Good point.  The only other reason for adding it would be if there were any data points that a Director would have but not an Actor that we would want to track.  But I dont think that there is anything useful in that.  I have no problem combining them into the one table

**Review by pt-repos — CHANGES_REQUESTED** [review]
ActorID and DirectorID should be PersonID. Apart from that looks good

**Comment by pt-repos** [comment]
> ActorID and DirectorID should be PersonID. Apart from that looks good

never mind. My mistake. didn't see the foreign key reference.

**Review by davidallen1 — CHANGES_REQUESTED** [review]
I looked it up and found that having NOT NULL PRIMARY KEY is redundant. 

"A primary key constraint combines a NOT NULL constraint and a unique constraint in a single declaration. That is, it prohibits multiple rows from having the same value in the same column or combination of columns and prohibits values from being null."
https://docs.oracle.com/cd/B19306_01/server.102/b14200/clauses002.htm

**Comment by brewgator** [comment]
> I looked it up and found that having NOT NULL PRIMARY KEY is redundant.
> 
> "A primary key constraint combines a NOT NULL constraint and a unique constraint in a single declaration. That is, it prohibits multiple rows from having the same value in the same column or combination of columns and prohibits values from being null."
> https://docs.oracle.com/cd/B19306_01/server.102/b14200/clauses002.htm

Cool.  I fixed it.

**Pull request merged**
